require 'test/unit' 

require 'primitives/test_note'
require 'primitives/test_octave'
require 'primitives/test_duration'
require 'primitives/test_bar'
require 'test_token'
require 'test_parser'
require 'test_note_bucket'
require 'test_factory'
